Finally added C.
MintzyG/Lets-Learn pull request #23
Opened 2023-04-08 02:22 UTC by grhifen

2023-04-08 02:23 UTC, MintzyG commented
Triste que você quebrou a sequência @grhifen  :(

2023-04-08 02:26 UTC, MintzyG requested changes
Remove unnecessary folders from c builds 'FileContentIndex' ; 'v17'
Remove unnecessary files 'VSWorkspaceState.json' 'slnx.qlite'
Add .lock ; .vsidx ; .suo ; .sqlite files to gitignore and remove these files

2023-04-08 16:27 UTC, grhifen commented
I hate VS Studio.

2023-04-09 14:32 UTC, MintzyG approved these changes

2023-04-09 14:32 UTC, merged